resolver: nightly-2019-03-15

packages:
  - .
  - ../web-page
  - ../svg-tree

extra-deps:
  - git: https://github.com/tonyday567/numhask.git
    commit: 717b02421d57b61890f21b9102c262628a98c968
    subdirs:
      - numhask
      - numhask-prelude
      - numhask-space
  - lucid-svg-0.7.0.0
  - generic-lens-1.1.0.0
  - git: https://github.com/ku-fpg/javascript-bridge.git
    commit: bb72dbb7d2f6376353f67aec6c251271ffb055d5
  - git: https://github.com/tonyday567/box.git
    commit: 542dec0c31060e4d12c5aa949ced8d5813827b7e
  #- git: https://github.com/tonyday567/web-page.git
  #  commit: 8119903dce36766179dc99770b18bf22f4679b38

allow-newer: true
